@startuml Fobnail Token Provisioning

skinparam LegendBorderThickness 0
skinparam LegendBackgroundColor #white
skinparam style strictuml
participant "Platform"
participant "Fobnail Token" as FT
participant "Platform Owner" as PO

legend top left
    K<sub>priv</sub>(X) - Sign X with P<sub>priv</sub> key
    PO<sub>chain</sub> - Platform Owner Certificate Chain
    IE<sub>pub,priv</sub>(X) - Fobnail Identity/Encryption public and private key
    IE<sub>cert</sub> Fobnail Identity/Encryption certificate
    CSR(X) - Create a certificate signing request from X
endlegend

activate FT
activate PO

PO -> FT: PO<sub>chain</sub>
FT <- FT: Verifiy PO<sub>chain</sub>
FT <- FT: Generate IE<sub>priv,pub</sub>
FT --> PO: CSR(F<sub>meta</sub>, IE<sub>pub</sub>)
PO -> PO: PO<sub>priv</sub>(CSR(IE<sub>pub</sub>))
PO -> FT: IE<sub>cert</sub>
FT <- FT: Verify IE<sub>cert</sub>
FT --> PO: Status

@enduml
